### ISSUE TITLE
5.0.0-beta1 crashes on occasion

### ISSUE THREAD

**Issue by raelb** [jmerle/inkdrop-table-editor#4] opened 2020-08-06 16:27 UTC
Thanks, I did manage to install now.

I can't reproduce this consistently, but a couple of times inkdrop crashed when I start to make a table, i.e. press shift \ (for pipe). Crash means the UI goes white, but the main menu is still visible.

I was pressing keys like ctrl + / (toggle tree), then shift+\

I tried to reproduce it, but now it is behaving well. Perhaps you will come across it. :)

**Comment by jmerle** [comment] 2020-08-31 20:15
I've just updated to the stable v5 release and I cannot reproduce this issue, so I'm closing it.

**Closed as completed by jmerle** 2020-08-31 20:15 UTC
